version: "1.0"
services:
  #Levantamos el back
  webapi:
    build: ./WebApi
    ports:
      - "7157:80"
    image: a26087/proyecto-es-back

  #Levantamos el front
  frontproyectoes:
    build: ./FrontProyectoES
    ports:
      - "26087:80"
    image: a26087/proyecto-es-front

  #Levantamos la DDBB

  mongo:
    image: mongo
    restart: always
    ports:
      - "6543:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:6543/
