version: "1.0"
services:
  #Levantamos el back
  webapi:
    build: ./WebApi
    ports:
      - "7157:80"
    image: a26087/proyecto-es-back

  #Levantamos el front
  frontproyectoes:
    build: ./FrontProyectoES
    ports:
      - "26087:80"
    image: a26087/proyecto-es-front

  #Levantamos la DDBB

  db:
    image: mongo
    restart: always
    ports:
      - "6543:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes:
      - "./db:/data/db"
